//! Renders the two generated source files.

use std::collections::BTreeSet;
use std::fmt::Write;

use super::emit_enum::{Variant, emit_enum};
use super::java_consts::{JavaConst, camel_case};
use super::{Geometry, Row, rule_variants};
use crate::error::XtaskError;

const HEADER: &str = "\
// Generated by `cargo xtask catalog` from the pinned mil-sym-java files named in
// tools/oracle/pin.json (msd.txt, mse.txt, DrawRules.java, MODrawRules.java).
// Do not edit; see UPSTREAM.md.
";

/// Source of `src/generated/draw_rule.rs`.
pub(super) fn draw_rule_module(
    standard: &[JavaConst],
    metoc: &[JavaConst],
) -> Result<String, XtaskError> {
    let mut out = String::from(HEADER);
    out.push_str("\n//! Draw-rule names declared by upstream's `DrawRules` and `MODrawRules`.\n\n");
    emit_enum(
        &mut out,
        "DrawRule",
        "Draw rule of a control measure (symbol set 25), named as in upstream's `DrawRules`.",
        &rule_variants(standard),
    )?;
    out.push('\n');
    emit_enum(
        &mut out,
        "MoDrawRule",
        "Draw rule of a METOC symbol (sets 45 and 46), named as in upstream's `MODrawRules`.",
        &rule_variants(metoc),
    )?;
    Ok(out)
}

/// Source of `src/generated/catalog.rs`.
pub(super) fn catalog_module(
    rows: &[Row],
    modifiers: &BTreeSet<&str>,
) -> Result<String, XtaskError> {
    let mut out = String::from(HEADER);
    out.push_str(
        "\n//! Catalog rows and modifier keys extracted from upstream's symbol tables.\n\n",
    );
    out.push_str("use super::draw_rule::{DrawRule, MoDrawRule};\n");
    out.push_str(
        "use crate::catalog::{CatalogDrawRule, CatalogEntry, GeometryKind, VersionSet};\n\n",
    );
    let variants = modifier_variants(modifiers)?;
    emit_enum(
        &mut out,
        "ModifierKey",
        "Modifier key a catalog entry accepts, named as in upstream's data tables.",
        &variants,
    )?;
    out.push_str("\n/// Catalog rows ordered by `(symbol_set, entity, first version)`.\n");
    out.push_str("pub(crate) static ENTRIES: &[CatalogEntry] = &[\n");
    for row in rows {
        writeln!(out, "    {},", entry(row))?;
    }
    out.push_str("];\n");
    Ok(out)
}

fn modifier_variants(modifiers: &BTreeSet<&str>) -> Result<Vec<Variant>, XtaskError> {
    let variants: Vec<Variant> = modifiers
        .iter()
        .map(|token| Variant {
            ident: camel_case(token),
            name: (*token).to_owned(),
            doc: format!("Upstream modifier `{token}`."),
        })
        .collect();
    let idents: BTreeSet<&str> = variants.iter().map(|v| v.ident.as_str()).collect();
    if idents.len() != variants.len() {
        return Err(XtaskError::Invariant(
            "two modifier tokens map to the same variant".to_owned(),
        ));
    }
    Ok(variants)
}

fn entry(row: &Row) -> String {
    let path: Vec<String> = row.path.iter().map(|p| format!("{p:?}")).collect();
    let mods: Vec<String> = row
        .modifiers
        .iter()
        .map(|m| format!("ModifierKey::{}", camel_case(m)))
        .collect();
    let geometry = match row.geometry {
        Geometry::Point => "Point",
        Geometry::Line => "Line",
        Geometry::Area => "Area",
    };
    let rule = if row.symbol_set == 25 {
        format!("CatalogDrawRule::Standard(DrawRule::{})", row.draw_rule)
    } else {
        format!("CatalogDrawRule::Metoc(MoDrawRule::{})", row.draw_rule)
    };
    format!(
        "CatalogEntry {{ symbol_set: {}, entity: {}, name: {:?}, path: &[{}], versions: VersionSet::from_bits({:#06x}), geometry: GeometryKind::{geometry}, draw_rule: {rule}, modifiers: &[{}] }}",
        row.symbol_set,
        row.entity,
        row.name,
        path.join(", "),
        row.versions,
        mods.join(", "),
    )
}
