//! Generates `src/generated/references.rs` from `tools/oracle/references.json`,
//! where `tools/standards/references.py` records, per symbol, the table, PDF
//! page and printed draw rule of each standard that defines it.

use std::fmt::Write;
use std::fs;
use std::path::Path;

use serde_json::Value;

use crate::error::XtaskError;

const INPUT: &str = "tools/oracle/references.json";
const OUTPUT: &str = "src/generated/references.rs";

/// Documents in the JSON and the editions they define.
const DOCUMENTS: &[(&str, &str)] = &[
    ("mil-std-2525d-ch1", "Mil2525Dch1"),
    ("mil-std-2525e-ch1", "Mil2525Ech1"),
];

pub(crate) fn run() -> Result<String, XtaskError> {
    let manifest = Path::new(env!("CARGO_MANIFEST_DIR"));
    let root = manifest
        .parent()
        .ok_or_else(|| XtaskError::Root(manifest.to_path_buf()))?;
    let path = root.join(INPUT);
    let text = fs::read_to_string(&path).map_err(|source| XtaskError::Read {
        path: path.clone(),
        source,
    })?;
    let json: Value =
        serde_json::from_str(&text).map_err(|source| XtaskError::Json { path, source })?;
    let mut rows = Vec::new();
    for (document, edition) in DOCUMENTS {
        let entries = json
            .get(*document)
            .and_then(Value::as_object)
            .ok_or_else(|| XtaskError::Invariant(format!("{INPUT} has no {document}")))?;
        for (key, entry) in entries {
            rows.push(row(document, edition, key, entry)?);
        }
    }
    rows.sort();
    let mut out = String::from(
        "// Generated by `cargo xtask references` from tools/oracle/references.json.\n\
         // Do not edit; see UPSTREAM.md.\n\n\
         //! Where each standard defines each graphic.\n\n\
         use crate::standard::StandardVersion::{self, Mil2525Dch1, Mil2525Ech1};\n\
         use crate::support::StandardRef;\n\n\
         /// `(edition, symbol set, entity, reference)`, sorted.\n\
         pub(crate) static REFERENCES: &[(StandardVersion, u8, u32, StandardRef)] = &[\n",
    );
    for (_, line) in &rows {
        writeln!(out, "    {line},")?;
    }
    out.push_str("];\n");
    let target = root.join(OUTPUT);
    fs::write(&target, out).map_err(|source| XtaskError::Write {
        path: target,
        source,
    })?;
    Ok(format!("references: {} entries", rows.len()))
}

/// One reference as a sort key and a Rust tuple expression.
fn row(
    document: &str,
    edition: &str,
    key: &str,
    entry: &Value,
) -> Result<((usize, u8, u32), String), XtaskError> {
    let bad = || XtaskError::Invariant(format!("{INPUT}: {document} {key} is malformed"));
    let (set, entity) = key.split_once(':').ok_or_else(bad)?;
    let set: u8 = set.parse().map_err(|_| bad())?;
    let entity: u32 = entity.parse().map_err(|_| bad())?;
    let table = entry.get("table").and_then(Value::as_str).ok_or_else(bad)?;
    let page = entry
        .get("pdf_page")
        .and_then(Value::as_u64)
        .ok_or_else(bad)?;
    let rule = match entry.get("draw_rule") {
        Some(Value::String(r)) => format!("Some({r:?})"),
        Some(Value::Null) | None => "None".to_owned(),
        Some(_) => return Err(bad()),
    };
    let order = DOCUMENTS
        .iter()
        .position(|(d, _)| *d == document)
        .unwrap_or(0);
    Ok((
        (order, set, entity),
        format!(
            "({edition}, {set}, {entity}, StandardRef {{ document: {document:?}, table: {table:?}, pdf_page: {page}, draw_rule: {rule} }})"
        ),
    ))
}
