//! `cargo xtask specs`: declares every multipoint graphic the oracle renders
//! (`tools/oracle/cases/all.tsv`) and the ported renderer matches — that is,
//! whose oracle case is not in `tests/fixtures/oracle/unimplemented.txt` —
//! into `src/generated/specs.rs`. Graphics built by milgraphics' own
//! families are declared by hand and left out.

mod rules;

use std::collections::BTreeSet;
use std::fmt::Write;
use std::fs;
use std::path::Path;

use crate::catalog::{self, Row};
use crate::error::XtaskError;

const CASES: &str = "tools/oracle/cases/all.tsv";
const UNIMPLEMENTED: &str = "tests/fixtures/oracle/unimplemented.txt";
const OUTPUT: &str = "src/generated/specs.rs";

/// Control measures with a hand-written family in `src/family`.
const HAND_BUILT: &[u32] = &[140_300, 120_200, 151_403, 170_100, 242_200, 270_601];

pub(crate) fn run() -> Result<String, XtaskError> {
    let root = catalog::root()?;
    let rows = catalog::rows(&root)?;
    let cases = read(&root, CASES)?;
    let pending: BTreeSet<String> = lines(&read(&root, UNIMPLEMENTED)?)
        .map(str::to_owned)
        .collect();
    let mut out = String::from(
        "// Generated by `cargo xtask specs` from tools/oracle/cases/all.tsv, the\n\
         // catalog and tests/fixtures/oracle/unimplemented.txt. Do not edit; see UPSTREAM.md.\n\n\
         //! Graphics drawn by the ported upstream renderer that match the oracle.\n\n\
         use crate::modifier::ModifierField as M;\n\
         use crate::standard::StandardVersion::{Mil2525Dch1, Mil2525Ech1};\n\
         use crate::support::table::{MANY, list, opt, ported};\n\
         use crate::support::SymbolSpec;\n\n\
         pub(crate) static SPECS: &[SymbolSpec] = &[\n",
    );
    let mut count = 0;
    for case in lines(&cases).filter_map(|l| l.split('\t').next()) {
        let Some((set, entity, version)) = base_case(case) else {
            continue;
        };
        if pending.contains(case) || (set == 25 && HAND_BUILT.contains(&entity)) {
            continue;
        }
        let row = rows
            .iter()
            .find(|r| r.symbol_set == set && r.entity == entity && r.versions >> version & 1 == 1)
            .ok_or_else(|| XtaskError::Invariant(format!("{case} is not in the catalog")))?;
        writeln!(out, "    {},", declaration(row, version))?;
        count += 1;
    }
    out.push_str("];\n");
    let target = root.join(OUTPUT);
    fs::write(&target, out).map_err(|source| XtaskError::Write {
        path: target,
        source,
    })?;
    Ok(format!("specs: {count} ported graphics declared"))
}

fn read(root: &Path, rel: &str) -> Result<String, XtaskError> {
    catalog::read_file(&root.join(rel))
}

fn lines(text: &str) -> impl Iterator<Item = &str> {
    text.lines()
        .map(str::trim)
        .filter(|l| !l.is_empty() && !l.starts_with('#'))
}

/// `(symbol set, entity, version code)` of a base case id such as
/// `25140300-d`; variants (`-anticipated`, `-s100k`) are not declarations.
fn base_case(id: &str) -> Option<(u8, u32, u32)> {
    let (code, edition) = id.split_once('-')?;
    let version = match edition {
        "d" => 11,
        "e" => 15,
        _ => return None,
    };
    let set = code.get(..2)?.parse().ok()?;
    let entity = code.get(2..)?.parse().ok()?;
    Some((set, entity, version))
}

fn declaration(row: &Row, version: u32) -> String {
    let edition = if version == 11 {
        "Mil2525Dch1"
    } else {
        "Mil2525Ech1"
    };
    let (min, max) = if row.symbol_set == 25 {
        rules::cm_points(&row.draw_rule, u8::try_from(version).unwrap_or(0))
    } else {
        rules::metoc_points(&row.draw_rule)
    };
    let (am, an) = if row.symbol_set == 25 {
        rules::required_counts(&row.draw_rule)
    } else {
        (0, 0)
    };
    let mut fields: Vec<String> = Vec::new();
    let mut listed: BTreeSet<&str> = row.modifiers.iter().map(String::as_str).collect();
    for (field, needed) in [("AM", am), ("AN", an)] {
        if needed > 0 {
            listed.remove(field);
            fields.push(format!("list(M::{field}, true, {needed}, MANY)"));
        }
    }
    for field in listed {
        fields.push(match field {
            "AM" | "AN" | "X" => format!("list(M::{field}, false, 1, MANY)"),
            _ => format!("opt(M::{field})"),
        });
    }
    format!(
        "ported({edition}, {}, {}).points({min}, {max}).amplifiers(&[{}])",
        row.symbol_set,
        row.entity,
        fields.join(", ")
    )
}
