//! `cargo xtask specs`: declares every multipoint graphic the oracle renders
//! (`tools/oracle/cases/all.tsv`) and the ported renderer matches — that is,
//! whose oracle case is not in `tests/fixtures/oracle/unimplemented.txt` —
//! into `src/generated/specs.rs`. Graphics built by milgraphics' own
//! families are declared by hand and left out, and so are graphics the
//! standard does not define as multipoint graphics (no row, or a
//! single-point rule in its row), which stay in the unimplemented list.
//!
//! The APP-6(D) text is not available, so APP-6(D) graphics are declared on
//! agreement with the oracle alone. APP-6(E) graphics need a row in its
//! text, which prints draw rules as prose, so both use the draw rule
//! upstream's catalog gives. APP-6 graphics are drawn by the ported renderer
//! throughout.

mod fields;
mod rules;

use std::collections::BTreeSet;
use std::fmt::Write;
use std::fs;
use std::path::Path;

use crate::catalog::{self, Row};
use crate::error::XtaskError;

const CASES: &str = "tools/oracle/cases/all.tsv";
const REFERENCES: &str = "tools/oracle/references.json";
/// Draw rules of single-point icons, drawn by milsymbol rather than here.
const SINGLE_POINT_RULES: &[&str] = &["Point1", "Point2", "Point3", "Point7"];
const UNIMPLEMENTED: &str = "tests/fixtures/oracle/unimplemented.txt";
const OUTPUT: &str = "src/generated/specs.rs";

/// Control measures with a hand-written family in `src/family`, and the
/// version codes they are hand-built for.
const HAND_BUILT: &[(u32, &[u32])] = &[
    (140_300, &[11, 15]),
    (120_200, &[11, 15]),
    (151_403, &[11, 15]),
    (170_100, &[11, 15, 16]),
    (242_200, &[11, 15]),
    (270_601, &[11, 15]),
    (170_200, &[15, 16]),
    (170_300, &[15, 16]),
    (170_400, &[15, 16]),
    (170_500, &[15, 16]),
    (170_600, &[15, 16]),
    (170_700, &[15, 16]),
];

pub(crate) fn run() -> Result<String, XtaskError> {
    let root = catalog::root()?;
    let rows = catalog::rows(&root)?;
    let cases = read(&root, CASES)?;
    let pending: BTreeSet<String> = lines(&read(&root, UNIMPLEMENTED)?)
        .map(str::to_owned)
        .collect();
    let path = root.join(REFERENCES);
    let references: serde_json::Value = serde_json::from_str(&read(&root, REFERENCES)?)
        .map_err(|source| XtaskError::Json { path, source })?;
    let mut out = String::from(
        "// Generated by `cargo xtask specs` from tools/oracle/cases/all.tsv, the\n\
         // catalog and tests/fixtures/oracle/unimplemented.txt. Do not edit; see UPSTREAM.md.\n\n\
         //! Graphics drawn by the ported upstream renderer that match the oracle.\n\n",
    );
    let mut body = String::new();
    let mut count = 0;
    for case in lines(&cases).filter_map(|l| l.split('\t').next()) {
        let Some((set, entity, version)) = base_case(case) else {
            continue;
        };
        let row = rows
            .iter()
            .find(|r| r.symbol_set == set && r.entity == entity && r.versions >> version & 1 == 1)
            .ok_or_else(|| XtaskError::Invariant(format!("{case} is not in the catalog")))?;
        let multipoint = match document(version) {
            Some(document) => in_standard(&references, document, set, entity),
            None => !SINGLE_POINT_RULES.contains(&row.draw_rule.as_str()),
        };
        let hand_built = set == 25
            && HAND_BUILT
                .iter()
                .any(|(e, versions)| *e == entity && versions.contains(&version));
        if pending.contains(case) || hand_built || !multipoint {
            continue;
        }
        writeln!(body, "    {},", declaration(row, version))?;
        count += 1;
    }
    if count > 0 {
        out.push_str(
            "use crate::modifier::ModifierField as M;\n\
             use crate::standard::StandardVersion::{App6D, App6Ech2, Mil2525Dch1, Mil2525Ech1};\n\
             use crate::support::table::{MANY, list, opt, ported};\n",
        );
    }
    out.push_str(
        "use crate::support::SymbolSpec;\n\npub(crate) static SPECS: &[SymbolSpec] = &[\n",
    );
    out.push_str(&body);
    out.push_str("];\n");
    let target = root.join(OUTPUT);
    fs::write(&target, out).map_err(|source| XtaskError::Write {
        path: target,
        source,
    })?;
    Ok(format!("specs: {count} ported graphics declared"))
}

/// The standard text cited for a version code, if one is available.
fn document(version: u32) -> Option<&'static str> {
    match version {
        11 => Some("mil-std-2525d-ch1"),
        15 => Some("mil-std-2525e-ch1"),
        16 => Some("app-06-e-v2"),
        _ => None,
    }
}

/// Whether the standard defines the graphic as one drawn from several
/// points: it has a row, and the row does not print a single-point rule.
fn in_standard(references: &serde_json::Value, document: &str, set: u8, entity: u32) -> bool {
    let Some(row) = references
        .get(document)
        .and_then(|d| d.get(format!("{set}:{entity}")))
    else {
        return false;
    };
    let printed = row.get("draw_rule").and_then(serde_json::Value::as_str);
    !printed.is_some_and(|rule| SINGLE_POINT_RULES.contains(&rule))
}

fn read(root: &Path, rel: &str) -> Result<String, XtaskError> {
    catalog::read_file(&root.join(rel))
}

fn lines(text: &str) -> impl Iterator<Item = &str> {
    text.lines()
        .map(str::trim)
        .filter(|l| !l.is_empty() && !l.starts_with('#'))
}

/// `(symbol set, entity, version code)` of a base case id such as
/// `25140300-d`; variants (`-anticipated`, `-s100k`) are not declarations.
fn base_case(id: &str) -> Option<(u8, u32, u32)> {
    let (code, edition) = id.split_once('-')?;
    let version = match edition {
        "app6d" => 10,
        "d" => 11,
        "e" => 15,
        "app6e" => 16,
        _ => return None,
    };
    let set = code.get(..2)?.parse().ok()?;
    let entity = code.get(2..)?.parse().ok()?;
    Some((set, entity, version))
}

fn declaration(row: &Row, version: u32) -> String {
    let edition = match version {
        10 => "App6D",
        11 => "Mil2525Dch1",
        15 => "Mil2525Ech1",
        _ => "App6Ech2",
    };
    let (min, max) = if row.symbol_set == 25 {
        rules::cm_points(&row.draw_rule, u8::try_from(version).unwrap_or(0))
    } else {
        rules::metoc_points(&row.draw_rule)
    };
    let (am, an) = if row.symbol_set == 25 {
        rules::required_counts(&row.draw_rule)
    } else {
        (0, 0)
    };
    let mut fields: Vec<String> = Vec::new();
    let mut listed: BTreeSet<&str> = row.modifiers.iter().map(String::as_str).collect();
    listed.extend(fields::added(version, row.symbol_set, row.entity));
    for (field, needed) in [("AM", am), ("AN", an)] {
        if needed > 0 {
            listed.remove(field);
            fields.push(format!("list(M::{field}, true, {needed}, MANY)"));
        }
    }
    for field in listed {
        fields.push(match field {
            "AM" | "AN" | "X" => format!("list(M::{field}, false, 1, MANY)"),
            _ => format!("opt(M::{field})"),
        });
    }
    format!(
        "ported({edition}, {}, {}).points({min}, {max}).amplifiers(&[{}])",
        row.symbol_set,
        row.entity,
        fields.join(", ")
    )
}
