//! The line-type groups that `clsUtilityCPOF` handles alike.

use crate::engine::tactical_lines::*;

/// Circles whose radius is AM.
pub(super) const CIRCLES: &[i32] = &[
    CIRCULAR,
    PBS_CIRCLE,
    BDZ,
    BBS_POINT,
    FSA_CIRCULAR,
    NOTACK,
    ACA_CIRCULAR,
    FFA_CIRCULAR,
    NFA_CIRCULAR,
    RFA_CIRCULAR,
    PAA_CIRCULAR,
    ATI_CIRCULAR,
    CFFZ_CIRCULAR,
    SENSOR_CIRCULAR,
    CENSOR_CIRCULAR,
    DA_CIRCULAR,
    CFZ_CIRCULAR,
    ZOR_CIRCULAR,
    TBA_CIRCULAR,
    TVAR_CIRCULAR,
    KILLBOXBLUE_CIRCULAR,
    KILLBOXPURPLE_CIRCULAR,
];

/// Ellipses: AM and AM1 are the semi-axes, AN the rotation.
pub(super) const ELLIPSES: &[i32] = &[
    LAUNCH_AREA,
    DEFENDED_AREA_CIRCULAR,
    SHIP_AOI_CIRCULAR,
    PBS_ELLIPSE,
];

/// Rectangles drawn about the segment between two anchor points, AM wide.
pub(super) const SEGMENT_RECTANGLES: &[i32] = &[
    PAA_RECTANGULAR,
    FSA_RECTANGULAR,
    SHIP_AOI_RECTANGULAR,
    DEFENDED_AREA_RECTANGULAR,
    FFA_RECTANGULAR,
    ACA_RECTANGULAR,
    NFA_RECTANGULAR,
    RFA_RECTANGULAR,
    ATI_RECTANGULAR,
    CFFZ_RECTANGULAR,
    SENSOR_RECTANGULAR,
    CENSOR_RECTANGULAR,
    DA_RECTANGULAR,
    CFZ_RECTANGULAR,
    ZOR_RECTANGULAR,
    TBA_RECTANGULAR,
    TVAR_RECTANGULAR,
    KILLBOXBLUE_RECTANGULAR,
    KILLBOXPURPLE_RECTANGULAR,
];

/// Line types whose fill is a separate shape (`LinesWithSeparateFill`).
pub(super) const SEPARATE_FILL: &[i32] = &[
    OBSFAREA,
    OBSAREA,
    STRONG,
    ZONE,
    FORT_REVD,
    FORT,
    ENCIRCLE,
    FIX,
    BOUNDARY,
    FLOT,
    LC,
    PL,
    DECISION_LINE,
    FEBA,
    LL,
    EWL,
    AC,
    MRR,
    SL,
    TC,
    SAAFR,
    SC,
    LLTR,
    DIRATKAIR,
    DIRATKGND,
    DIRATKSPT,
    INFILTRATION,
    FCL,
    HOLD,
    BRDGHD,
    HOLD_GE,
    BRDGHD_GE,
    LOA,
    LOD,
    LDLC,
    PLD,
    RELEASE,
    HOL,
    BHL,
    LINE,
    ABATIS,
    ATDITCH,
    ATDITCHC,
    ATDITCHM,
    ATWALL,
    MNFLDFIX,
    UNSP,
    SFENCE,
    DFENCE,
    DOUBLEA,
    LWFENCE,
    HWFENCE,
    SINGLEC,
    DOUBLEC,
    TRIPLE,
    FORTL,
    LINTGT,
    LINTGTS,
    FSCL,
    BCL_REVD,
    BCL,
    ICL,
    IFF_OFF,
    IFF_ON,
    GENERIC_LINE,
    CFL,
    TRIP,
    NFL,
    MFP,
    RFL,
    MSR,
    MSR_ONEWAY,
    MSR_TWOWAY,
    MSR_ALT,
    ASR,
    ASR_ONEWAY,
    ASR_TWOWAY,
    ASR_ALT,
    TRAFFIC_ROUTE,
    TRAFFIC_ROUTE_ONEWAY,
    TRAFFIC_ROUTE_ALT,
];
